<?xml version="1.0"?>
<package format="2">
  <name>testing</name>
  <version>0.1.0</version>
  <description>Dummy nodes to test interfaces</description>

  <maintainer email="sebastien.darche@polymtl.ca">Sébastien Darche</maintainer>

  <license>MIT</license>

  <author email="sebastien.darche@polymtl.ca">Sébastien Darche</author>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>serial</depend>
  <build_depend>detection</build_depend>
  <exec_depend>detection</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
